# Generated by Django 5.1.4 on 2025-05-24 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_image', models.ImageField(upload_to='receipts/')),
                ('extracted_text', models.TextField(blank=True, null=True)),
                ('items', models.JSONField(blank=True, null=True)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
