# Generated by Django 5.2.1 on 2025-09-19 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("receipts", "0003_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="receipt",
            name="uploaded_image",
        ),
        migrations.AddField(
            model_name="receipt",
            name="uploaded_image_url",
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
