# Generated by Django 5.2.1 on 2025-11-06 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FreedomConferenceRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("phone_number", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("is_minister", models.BooleanField()),
                ("ministry_name", models.CharField(blank=True, max_length=255)),
                ("ministry_address", models.CharField(blank=True, max_length=255)),
                ("is_first_time", models.BooleanField()),
                ("expectations", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Freedom Conference Registration",
                "verbose_name_plural": "Freedom Conference Registrations",
                "ordering": ["-created_at"],
            },
        ),
    ]
