# Generated by Django 5.1.4 on 2025-05-24 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('date', models.DateTimeField()),
                ('narration', models.TextField()),
                ('account_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('sender_receiver', models.CharField(blank=True, max_length=255, null=True)),
                ('reference_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
