# Generated by Django 5.1.4 on 2025-07-09 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0005_transactioncategory_transaction_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="bank_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
