# Generated by Django 5.1.4 on 2025-07-09 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0007_rawemail2"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RawEmail2",
        ),
    ]
