# Generated by Django 5.2.1 on 2025-07-24 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0010_transaction_is_manually_categorized"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParserFunction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bank_name", models.CharField(max_length=100, unique=True)),
                (
                    "parser_code",
                    models.TextField(
                        help_text="The Python code for the parsing function."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name="rawemail",
            name="parsing_method",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("ai_success", "AI Success"),
                    ("html_parser_success", "HTML Parser Success"),
                    ("ai_failed", "AI Failed to Parse"),
                    (
                        "creation_failed_data_error",
                        "Transaction Creation Failed (Data Error)",
                    ),
                    (
                        "creation_failed_unknown",
                        "Transaction Creation Failed (Unknown Error)",
                    ),
                ],
                default="none",
                max_length=50,
            ),
        ),
    ]
