# Generated by Django 5.2.1 on 2025-07-24 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0011_parserfunction_alter_rawemail_parsing_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="rawemail",
            name="bank_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="rawemail",
            name="sent_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
