# Generated by Django 5.2.1 on 2025-08-12 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0012_rawemail_bank_name_rawemail_sent_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="rawemail",
            name="manual_review_needed",
            field=models.BooleanField(default=False),
        ),
    ]
