# Generated by Django 5.2.1 on 2025-08-15 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0013_rawemail_manual_review_needed"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="narration_cleaned",
            field=models.BooleanField(default=False),
        ),
    ]
