# Generated by Django 5.2.1 on 2025-09-15 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0014_transaction_narration_cleaned"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rawemail",
            name="parsing_method",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("dynamic_html_parser_success", "Dynamic HTML Parser Success"),
                    ("ai_generated_parser_success", "AI Generated Parser Success"),
                    ("ai_fallback_success", "AI Fallback Success"),
                    ("regex_fallback_success", "Regex Fallback Success"),
                    ("all_methods_failed", "All Methods Failed"),
                    (
                        "creation_failed_data_error",
                        "Transaction Creation Failed (Data Error)",
                    ),
                ],
                default="none",
                max_length=50,
            ),
        ),
    ]
