# Generated by Django 5.2.1 on 2025-09-16 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("transactions", "0015_alter_rawemail_parsing_method"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemFrequency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_description", models.CharField(max_length=255)),
                ("frequency", models.CharField(blank=True, max_length=50, null=True)),
                ("purchase_count", models.PositiveIntegerField(default=0)),
                ("last_purchased", models.DateTimeField(blank=True, null=True)),
                ("next_predicted_date", models.DateTimeField(blank=True, null=True)),
                ("confidence_score", models.FloatField(blank=True, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="transactions.transactioncategory",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "item_description")},
            },
        ),
        migrations.CreateModel(
            name="TransactionFrequency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("narration", models.CharField(max_length=255)),
                ("frequency", models.CharField(blank=True, max_length=50, null=True)),
                ("transaction_count", models.PositiveIntegerField(default=0)),
                ("last_transaction_date", models.DateTimeField(blank=True, null=True)),
                ("next_predicted_date", models.DateTimeField(blank=True, null=True)),
                ("confidence_score", models.FloatField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "narration")},
            },
        ),
    ]
